export const SERIES_STATUS = {
  UPCOMING: "UPCOMING",
  LIVE: "LIVE",
  COMPLETED: "COMPLETED",
};

export const SERIES_STATUS_OPTIONS = [
  SERIES_STATUS.UPCOMING,
  SERIES_STATUS.LIVE,
  SERIES_STATUS.COMPLETED,
];